apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 588738579508.dkr.ecr.us-east-1.amazonaws.com/gitops-ecr
        ports:
        - containerPort: 80