apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
images:
  - name: 588738579508.dkr.ecr.us-east-1.amazonaws.com/gitops-ecr
    newTag: latest